version: "3.9"

services:
  webapp:
    restart: always
    image: ijpatricio/simple-docker:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
