version: "3.9"

volumes:
  mysql_db:

services:
  webapp:
    image: simple-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "pnpm", "run", "dev" ]
    ports:
      - "80:3000"
    volumes:
      - .:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
